version: "3.0"

services:
  db:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - ./_docker/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: blogtest-db

  nginx:
    image: nginx:1.22.0
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
      - ./_docker/logs/nginx/:/var/log/nginx/
    container_name: blogtest-nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - db
    container_name: blogtest-app
    extra_hosts:
      - "internal.host:host-gateway"

  worker:
    build:
      context: .
      dockerfile: _docker/supervisor/Dockerfile
    volumes:
      - ./:/var/www/
      - ./_docker/supervisor/:/etc/supervisor
    ports:
      - "6001:6001"
    depends_on:
      - app
    command: supervisord
    container_name: blogtest-worker


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./_docker/redisdata:/data
    container_name: blogtest-redis

